tmdb api 요청 및 컴포넌트 수정
sjndowair/movvy pull request #7
Opened 2024-07-15 15:43 UTC by sjndowair

### 풀 리퀘스트 타입
> 하나 이상의 PR 타입을 선택해주세요.
- [x] Add Features
- [ ] Delete features
- [ ] Bug fix
- [ ] Chore jobs
- [ ] Update packages

### 반영 브랜치
> 작업한 브랜치와 작업 내역을 반영할 브랜치를 명세해주세요.
> _ex) feat/refactor-layout -> master_
>

### 변경 사항
> 풀 리퀘스트를 요청하는 코드 내용에 대해 간략하게 명세해주세요.
api로 받아온 정보 배치 및 기존 목업 컴포넌트 삭제 
>

### 특이 사항
> 
> 

### 스크린샷
>
>
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/b32bdf41-6b37-4013-9074-280b9c49a9ab">

2024-07-19 15:50 UTC, songforthemute requested changes
1. 컴포넌트 인터페이스 정의 및 분리
2. 변수, props, 컴포넌트 이름 다시 한번 더 고려해보기 + 고민 많이하기
3. 불필요한 깊은 depth의 마크업 지양
4. console.log는 테스트할때 열심히 쓰고, 지우기
5. 옵셔널 체이닝 + null 병합 연산자 잘 활용해서 예외처리, 에러처리 잘 하기
6. 배열 내부 요소들도 옵셔널 체이닝 할 수 있다.
7. 상수는 컴포넌트 바깥에 정의하고 가급적이면 분리할 것, 상태로 관리해야하는 요소라면 state로, 동적인 요소를 얻어오는 것에 불과하다면 함수로 분리하는 것을 고려하기
8. 매직 넘버 가급적이면 지양하기
9. 예외처리 잘하기! 꼭!
10. 브라우저 렌더링 파이프라인에 대해서 조금 더 공부하고, 생각해보기

2024-08-02 16:40 UTC, songforthemute commented
```ts
import { useEffect, useState } from "react";

import Layout from "../components/layout"; // 레이아웃 컴포넌트

import styled from "styled-components";

const ModalBackground = styled.div`
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 9999;
`;

const ModalContainer = styled.div`
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    z-index: 10000;
`;

const LOCAL_STORAGE_NOT_TODAY_KEY = "LOCAL_STORAGE_NOT_TODAY_KEY";

const getTodayDate = () => {
    return new Date().toLocaleDateString("ko-kr", {
        dateStyle: "medium",
    });
};

const Home = () => {
    const [isOpenModal, setIsOpenModal] = useState<boolean>(false);
    const [isCheckedNotToday, setIsCheckedNotToday] = useState<boolean>(false);

    const onCloseModal = () => {
        setIsOpenModal(false);

        if (isCheckedNotToday) {
            localStorage.setItem(LOCAL_STORAGE_NOT_TODAY_KEY, getTodayDate());
        }
    };

    useEffect(() => {
        const notTodayDate = localStorage.getItem(LOCAL_STORAGE_NOT_TODAY_KEY);

        if (!notTodayDate || notTodayDate !== getTodayDate()) {
            setIsOpenModal(true);
        }
    }, []);

    return (
        <Layout>
            {isOpenModal && (
                <ModalBackground
                    onClick={(e) => {
                        e.preventDefault();
                        e.stopPropagation();
                        onCloseModal();
                    }}
                >
                    <ModalContainer>
                        <label
                            onClick={(e) => {
                                e.preventDefault();
                                e.stopPropagation();
                                setIsCheckedNotToday((prev) => !prev);
                            }}
                        >
                            <input
                                type="checkbox"
                                checked={isCheckedNotToday}
                            />
                            <span style={{ color: "#000" }}>
                                오늘 하루 보지 않기
                            </span>
                        </label>
                    </ModalContainer>
                </ModalBackground>
            )}
        </Layout>
    );
};
```

2024-08-02 16:49 UTC, songforthemute commented
### 240802

> 1. svg 조금 더 공통화 _(굳이 styled한 컴포넌트일 필요가 없음)_
> 2. 변수/상수명 오탈자가 여전히 많이 존재함
> 3. 캐러셀 컴포넌트, 다른 컴포넌트도 그렇지만, 데이터는 페이지나 필요한 데에서 부르고, 컴포넌트는 받은 데이터를 잘 그려주고 상호작용에 유연할 수 있도록 분리하는 연습. 페이지와 컴포넌트의 역할 분담/분리.
> 4. 모달 _(cf. https://github.com/sjndowair/movvy/pull/7#issuecomment-2265771119)_
> 5. 디자인에 너무 신경쓰지 말 것. 디자인에 과하게 신경써서 애플리케이션이 빌딩이 안되고 있음.
> 6. 불편하거나 어색한 점이 생기면, 글로 정의하는 연습을 할 것. 그래야 구체적으로 내가 어떤 상황에 처해 있고, 어떤 방법을 쓸 수 있고를 판단하고, 설명할 수 있음.
> 7. 질문 좀 할 것..

2024-10-11 08:55 UTC, sjndowair commented
최종 수정

2024-10-11 08:57 UTC, merged